### ISSUE TITLE
Message for the whole class | ENTC B

### ISSUE THREAD

**Issue by meghanabhange** [meghanabhange/autographx#6]
A message for the class of ENTC B (for now--will move this to automated one later) :)

**Comment by Alankriti3107** [comment]
https://github.com/meghanabhange/autographx/labels/Content

**Comment by Alankriti3107** [comment]
1st August 2016. That was the day which marked the beginning of our engineering years for most of us. Some of us were nervous because we didn't know what to expect..some of us were disappointed because we couldn't get into IIT...some were dreading entering a girls college..some of us had remnants of the shattered dreams of careers and interests we couldn't purse, and well a few of us were actually excited to become engineers! Nevertheless, we all started this journey together with Kavita ma'am and Aparna ma'am as our mentors, having a special vada pav counter fo us, a horrible canteen, and a feeling of dread because we realised college is not what movies made it to be. Come July 2017 and the direct second year admissions joined us in this journey. Everything is just a blurry mess of countless memories from there. This yearbook is a collection of a few of those precious memories. 
“Yaadein mithai ke dabbe ki tarah hoti hain, ek baar khula toh sirf ek tukda nahi khaa paoge.”

**Comment by meghanabhange** [comment]
Great, I'll add this to the first page :)
